# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('registered_on', models.DateField(default=django.utils.timezone.now)),
                ('subscription_end', models.DateField(default=django.utils.timezone.now)),
                ('level', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('trust', models.PositiveSmallIntegerField(blank=True, default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField(default=django.utils.timezone.now)),
                ('body', models.TextField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='chat.Caller')),
            ],
        ),
    ]
