# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 19:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170404_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('registered_on', models.DateField(default=datetime.date(2017, 4, 17))),
                ('subscription_end', models.DateField(blank=True, default=datetime.date(2017, 5, 17))),
                ('level', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('trust', models.PositiveSmallIntegerField(blank=True, default=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
