# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20170417_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caller',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='caller',
            name='subscription_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
